# deploy/docker-compose.yml
version: '3.8'

services:
  backend:
    platform: linux/amd64   # <--- ADICIONE ESTA LINHA AQUI
    container_name: kanban-backend
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    volumes:
      - kanban_db:/app/
    restart: unless-stopped

  frontend:
    container_name: kanban-frontend
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  kanban_db: